### ISSUE TITLE
Investigate Why Upgrading Browserslist Config Breaks in Downstream Projects

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-application#109]
# Bug Report

## Description

Investigate why update browserslist-config-terra v1.2.0 to @cerner/browserslist-config-terra v^3.0.0 throws errors when running webpack.

See discussion on https://github.com/cerner/terra-application/pull/74

We need to figure this out to close #64 

## Steps to Reproduce

Follow steps outlined here to get started: https://github.com/cerner/terra-application/pull/74#pullrequestreview-474641279

## Expected Behavior

Terra-application's version of browserlist should not impact other project's webpack builds.

## Environment

* Node/npm Version: [e.g. Node 8/npm 5] lts/dubnium
* Webpack Version: ^4.43.0
* Operating System and version (desktop or mobile): Mac

## @ Mentions

@StephenEsser @avinashg1994

**Comment by pranav300** [comment]
The reason behind the errors in the terminal for the repo https://github.com/StephenEsser/browserslist-spike can be that we are not using a packed file to install `terra-application`. Just try with this `"terra-application": "https://github.com/cerner/terra-application/blob/update-browserslist-test/terra-application-1.35.0.tgz?raw=true"`, it worked for me.

Edit: It doesn't work until and unless we make `@cerner/browserslist-config-terra` as a strict dependency in terra-application.

**Comment by StephenEsser** [comment]
@pranav300 Can you explain what steps you took to get this working? 

The issue and terminal output was reproducible with both a git reference and a pack file using the browserlist-spike repository. Please see https://github.com/cerner/terra-application/pull/74#pullrequestreview-474641279 for more information. 

Example projects/branches would be helpful.

**Comment by pranav300** [comment]
I just ran `npm pack` on a copy of this branch [update-browserslist](https://github.com/cerner/terra-application/tree/update-browserslist) and referenced the .tgz file in the repo `browserslist-spike`.

**Comment by pranav300** [comment]
I couldn't find any source to validate, but maybe `webpack` reads `browserslist` in `package.json` of each dependency. So when it tries to read it for terra-application, there is an `extends @cerner/browserslist-config-terra`, which is not present in node_modules. Hence causes the project to break.

The solution that I and @StephenEsser thought about was to create a file `.browserslistrc` in the root folder, and pass `extends @cerner/browserslist-config-terra`, and remove browserslist from package.json. This file does not get imported into downstream projects, and wouldn't cause any break in them.

**Comment by emilyrohrbough** [comment]
> I couldn't find any source to validate, but maybe webpack reads browserslist in package.json of each dependency. So when it tries to read it for terra-application, there is an extends @cerner/browserslist-config-terra, which is not present in node_modules. Hence causes the project to break.


Looks like this is coming from Autoprefixer attempting to load the supported the supported browsers here:
- [Autoprefixers loading the browsers config](https://github.com/postcss/autoprefixer/blob/207f4ad1f3e0c1d580735cfcc484d2334e9b68f6/lib/autoprefixer.js#L103) (which isn't passed inf rom our webpack config, so it relies on .browserslistrc or the browserslist package.json key.
- [Browserslist used here](https://github.com/postcss/autoprefixer/blob/151f0980baa369d8b96944c71ae52daca96effe8/lib/browsers.js#L54)

In the browserslist module, since it wasn't passes the browsers to target, it searches the parents for it's configuration:
- [Browserlist loads the config](https://github.com/browserslist/browserslist/blob/master/index.js#L411)
- [Tries to find the config](https://github.com/browserslist/browserslist/blob/master/node.js#L223)
- Which then finds the nearest browserslist configuration
