### ISSUE TITLE
Provide a mechanism for consumers to provide a global error handler that gets executed on error boundaries

### ISSUE THREAD

**Issue by dkschoonover** [cerner/terra-application#15]
# Issue Description
Currently terra-application provides an error boundary, but when errors are caught they are suppressed from new relic.  New relic provides an API to log errors which could be used to forward errors if newrelic is present on the window.

https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/notice-error

**Comment by mjhenkes** [comment]
I cleared the milestone so that we could discuss if this is a bug (yes) :P

**Comment by nickpith** [comment]
I'm curious if there should also be a callback that applications or other components that build on top of terra-application can use to post errors to other sources other than New Relic.

**Comment by nickpith** [comment]
This way we are not locking everyone into New Relic support since the choice of observability framework changes like the wind.

**Comment by ryanthemanuel** [comment]
I updated the title of this to more accurately describe what we want to do (provide a mechanism for consumers to provide a global error handler that gets executed on error boundaries).
