### ISSUE TITLE
[ApplicationContainer][SPIKE] Investigate F6 region hopping within browsers

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-application#154]
# Story

## Description

As a developer, I want to investigate F6 region hopping within browsers...

## Motivation

So that we can make terra-application as accessible as possible.

## Definition of Done

We'll know we're done when we have determined the feasibility of doing this feature within a web browser.

## Details

We really just need to determine whether we're comfortable overriding browser features with our own key handling. If so, we likely need to integrate this behavior with the SkipToLinks component or create an altogether separate identification method to handle this feature.

**Comment by dkasper-was-taken** [comment]
Results of SPIKE included on associated closing issue.

Closing in favor of #196
