### ISSUE TITLE
[SPIKE] Investigate `fetch` usage in legacy browsers for TerraRequestor

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-application#159]
# Story

## Description

As a developer, I want to determine how best to use fetch APIs within our supported legacy browsers...

## Motivation

So that we have a consistent dependency for our async requests.

## Definition of Done

We'll know we're done when we have identified a shim/polyfill or ruled out fetch usage due to incompatibility.

**Comment by tbiethman** [comment]
### Tech Design

The purpose of this tech design is to define how fetch may be used across our supported browsers and how Terra may offer fetch as a first-class API. We have one good option for the former and many options for the latter.

My primary goal here is to provide something that is as similar to the native fetch implementations as possible.

#### Fetch Polyfills

Fetch has broad support across current browser versions. Given our support of IE10+, however, we need to add a fetch polyfill  in order to ensure proper support. The polyfills investigated include:

1. [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) - A fetch polyfill provided by github

* Pros:
  * Actively supported (last release 5 mo ago, limited issues/active PRs)
  * Good docs
  * IE10+ support
  * Polyfill + Ponyfill options (more on this below)
  * No dependencies
  * MIT license
* Cons:
  * Not all Fetch standard options are supported in this polyfill

2. [unfetch](https://www.npmjs.com/package/unfetch) - "Tiny 500b fetch "barely-polyfill""

* Pros:
  * It's smaller than whatwg-fetch
  * Mostly actively supported (last release 10 mo ago, moderate issues/active PRs)
  * IE8+ support
  * Polyfill + Ponyfill options (more on this below)
  * No dependencies
  * MIT licence
* Cons:
  * Very stripped down on the options front, to the point where it may be too limiting/different

**whatwg-fetch** has seemingly become the standard option. Other polyfills exist but have not been maintained. Given the support is has behind it and its broad similarities to the native fetch APIs, I feel like it's the best choice. I propose we add it as a dependency to terra-application.

#### Related Polyfills

Fetch and its polyfills require Promises, so we must ensure Promises are also polyfilled. We already do this, no changes are required.

To abort fetch requests, an [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) must be instantiated and given to the request. Like Fetch itself, AbortController has minimal support in older browsers and must be polyfilled if we expect consumers to cancel requests. I posit that we do expect that and thus should include an AbortController polyfill as well. The best option here is:

1. [abortcontroller-polyfill](https://www.npmjs.com/package/abortcontroller-polyfill)
* Pros
  * Supported (last release 2 months ago)
  * No dependencies
  * MIT licence
  * IE8+ support
  * Polyfill + Ponyfill options (more on this below)
* Cons
  * It's yet another polyfill
  
Others exist but generally aren't well supported or only have beta releases.

#### Terra's Fetch APIs

We have a Fetch polyfill and an AbortController polyfill nailed down. However, we have a number of options to expose them to terra-application's consumers. My proposal is to export the polyfill contents from terra-application as [ponyfills](https://ponyfoo.com/articles/polyfills-or-ponyfills).

```js
// terra-application/lib/fetch/index.js
export { AbortController } from 'abortcontroller-polyfill/dist/cjs-ponyfill';
export { fetch } from 'whatwg-fetch';
```

By not patching the global browser functionality, terra-application can limit its responsibilities and create a scope for its APIs. I prefer to be transparent here and explicitly tell consumers that by using these APIs, they are guaranteed to consume the ponyfill implementations. And given that whatwg-fetch isn't fully spec compliant, and given that browser support across the board may be inconsistent for some features, it benefits us and consumers to have a consistent API to expose.

We will need to add limited documentation as well, mostly redirecting consumers to the appropriate dependency's separate documentation.

##### Example Implementation

```jsx
import { fetch, AbortController } from '@cerner/terra-application/lib/fetch';

const ExampleComponent = () => {
  const [data, setData] = React.useState();
  const abortControllerRef = React.useRef();
  
  React.useEffect(() => {
    // window.fetch may or may not be defined depending on the browser
    // fetch from terra-application will always use the polyfill implementation
    
    abortControllerRef.current = new AbortController();
    
    fetch('/example/data', { signal: abortControllerRef.current.signal })
      .then(response => response.json())
      .then((data) => {
        setData(data); 
      })
      .catch(err => {
        if (err.name === 'AbortError') {
          console.log('aborted');
          abortControllerRef.current = undefined;
        }
      });
  }, [])

  return (
    <div>
      <p>{data ? JSON.stringify(data) : undefined}</p>
      <button 
        type="button" 
        onClick={() => { abortControllerRef.current ? abortControllerRef.current.abort() : undefined }
      >
        Abort
      </button>
    </div>
  );
};
```

**Comment by nickpith** [comment]
I don't really agree with making this a ponyfill instead of just a polyfill. The [Caveats](https://github.com/github/fetch#caveats) listed on whatwg-fetch are a very small minority of browsers and rare use cases. Just like we use Babel to promote the usage of modern Javascript and transpile for backward compatibility, we should be promoting the use of the web platform primitives like fetch where available and polyfilling the browsers that don't have it. 

What is the plan when we fully support fetch compliant browsers? Are we going to maintain this ponyfill until we can get every project to make a change to get off it?

I can see an argument for a fetch helper in terra-application to manage setting request headers, processing responses, etc to make using fetch easier. That could use this ponyfill approach if that is desired but I don't think terra-application should be providing fetch directly.

**Comment by tbiethman** [comment]
Including the polyfills within [webpack-config-terra](https://github.com/cerner/terra-toolkit/tree/main/packages/webpack-config-terra) is a viable option to make this more seamless. We just wouldn't be able to utilize fetch here or elsewhere without introducing a major version with that implicit dependency specified.

The maintenance cost of exposing the ponyfill would be minimal, but if we can avoid it altogether by scoping fetch usage to new package versions, I agree that would be best.

**Comment by mjhenkes** [comment]
We ended up having a discussion about if we added the polyfill, where would we add it.

Option 1:
Polyfill added to terra-application-base. Through detection of some type we would check if fetch exists and if it doesn't we will polyfill it, similar to how we polyfill intl.

Postive:
* no additional work from consumers

Negative:
* consumers can not opt out of the polyfill.
* terra-application-base doesn't use fetch directly so it feels a bit odd to be here.
* terra-application-base would have to be imported before fetch could be used.

Option 2: 
Polyfill added to webpack-config-terra. The polyfill would be added to the webpack config as an entry similar to how core-js polyfill is added.

Postive:
* no additional work from consumers.
* consumers could opt out of the polyfill if they know to remove the entry.

Negative:
* consumers could accidentally opt out of the polyfill by making bad assumptions about the entries.
* consumers would have to be using a derivative of webpack-config-terra or we have to patch back to terra-toolkit-boneyard.
* It feels odd to be adding explicit entries for polyfills in webpack. I think in my ideal webpack config, Webpack itself would break out chunks for shared polyfills between consumer specified entries.

Option 3: 
Available polyfills added by the individual application implementation (pct, terra-dev-site). We would document what polyfills are required and possibly provide the import that teams could use, but it would be up to the consuming team where and when to include it.

Positive:
* 100% controlled by the consumer (for good or bad)
* can be used whenever in the application lifecycle.
* consumer can choose to include it or not
* consumer could choose a completely different polyfill.

Negative:
* component teams could use fetch via terra-dev-site but may fail depending on the application 
* consumer could choose a completely different polyfill.

**Comment by nickpith** [comment]
Are you thinking option 3 is like react-app-polyfill from create-react-app?

See https://create-react-app.dev/docs/supported-browsers-features/#supported-browsers for their recommendation. 

I could see terra-application providing a default polyfill like that to provide an easy choice (and thus prevent anyone from looking for alternatives). It would then be on the application runtime (i.e. terra-dev-site, pct) to provide it. This way all the various plugins and parts of that application can be coded against modern browsers and not worry about it. 

I'm all for option 3 if that is what it is.

**Comment by mjhenkes** [comment]
@nickpith Yeah, exactly like that! I didn't know that existed but it's the same idea.

**Comment by tbiethman** [comment]
Added a rough prototype implementation of the potential polyfills package here: https://github.com/cerner/terra-application/tree/spike-159-fetch/packages/terra-application-polyfill

**Comment by nickpith** [comment]
👍

**Comment by tbiethman** [comment]
Following up on the 'terra-polyfill' package development here: https://github.com/cerner/terra-application/issues/158
