### ISSUE TITLE
[terra-application-v2][SPIKE] Integrate workspace into the application

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-application#202]
# Story

## Description

As a consumer of terra, I would like workspace to be available inside of terra-application

## Motivation

So that I can utilize the features of workspace inside of my application

## Definition of Done

We'll know we're done when workspace is integrated in the primary navigation layout, available across primary workspace items.

**Comment by dkasper-was-taken** [comment]
Investigation:
There are two broad categories of integrating workspace back into v1:

1) Wrap the child content passed into terra-application with the workspace-layout, and then pass that to the terra-application-navigation component. This is the simplest approach and does that involve changes to the terra-application-navigation component. One downside to this is that the skipToLinks are currently not dynamic and it would be difficult to add the new link for workspace. Another issue is that workspace would be placed inside the 'main' region, which would be incorrect as workspace is not directly tied to the main content and functions more as an aside.

2) Pull a copy of terra-application-navigation into terra-application. Replace the exisitng exports for terra-application-navigation with our local copy. Alter applicaton-navigation to allow for additional skipToLinks and for workspace content to live as a sibling to main content. This is a significantly  large charge, but would account for the a11y failings of approach one.

From offline discussion and testing the team as concluded that option 2 is best for our needs as we do not want to introduce changes into the terra repository that break or introduce new accessibility issues.

The next required aspect is going to be an exposed context that would allow consumers to toggle the workspace with their own custom button/header. Given the current structure of headers and toolbars we cannot guarantee that adding a new toolbar to toggle the workspace would display in the proper hierarchical order, which could causes breaks in functionality for existing consumers. So a context for consumers is necessary.

I will be logging 3 different issues accordingly.
Port/fork application navigation into terra-application:
#222 
Create a new workspace context within terra-application:
#223 
Alter the workspace layout to fit into main region of application navigation:
#224
