### ISSUE TITLE
Application Event Emitter

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-application#23]
# Feature Request

## Description
 Provide a user friendly event emitter to enable communication between otherwise unrelated components within an application. This should be a global api available to all components.

We could wrap dom events and clean up the API.
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Overview_of_Events_and_Handlers

Or we could create a purely javascript pubsub.

There are open source options we should consider either providing directly or wrapping.
https://www.npmjs.com/package/events
https://www.npmjs.com/package/eventemitter3

**Comment by supreethmr** [comment]
Both approach has their own pros and cons w.r.t to creating event emitter. 

> We could wrap dom events and clean up the API.

With these approach we can create event-emitter API by using Dom Event interface / Custom Event interface. Both Event interface and CustomEvent interface has limited support for IE as mentioned in the Browser_compatibility table 
Event :  https://developer.mozilla.org/en-US/docs/Web/API/Event#Browser_compatibility
Custom Event : https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Browser_compatibility

Notably, both has no support for creating new instances (constructor) in IE. making it difficult to create compatible  event emitter.

> Or we could create a purely javascript pubsub.

EventEmitter3 is compatible with most of the modern browser and IE as well. but the only cons of EventEmitter3 is that Events cannot be canceled via event.preventDefault(). This ability is configurable with the cancelable property when object created using CustomEvent constructor 
```jsx
new CustomEvent(eventName, { detail, cancelable: true })
```
but i am not sure if EventEmitter3 provides provision to configure event properties unlike Dom and CustomEvent and also we will be dependent on yet another npm package.

with my limited knowledge on the use case scenario of event emitters in application components, I am not able to make decision among two approaches. So any information which helps me in understanding  the need of event emitter in terra-Application might help me to proceed further.

**Comment by yuderekyu** [comment]
> Both Event interface and CustomEvent interface has limited support for IE as mentioned in the Browser_compatibility table

fyi for ie compatibility, here's how we've initialized events without polyfilling the event constructor. [src](https://github.com/cerner/terra-application/blob/master/tests/wdio/application-base/private/test-overrides-spec.js#L6-L7)
```js
const event = document.createEvent('Event');
event.initEvent(eventName, true, true);
```

**Comment by supreethmr** [comment]
> > Both Event interface and CustomEvent interface has limited support for IE as mentioned in the Browser_compatibility table
> 
> fyi for ie compatibility, here's how we've initialized events without polyfilling the event constructor. [src](https://github.com/cerner/terra-application/blob/master/tests/wdio/application-base/private/test-overrides-spec.js#L6-L7)
> 
> ```js
> const event = document.createEvent('Event');
> event.initEvent(eventName, true, true);
> ```

Thank you..! let me try adding it this way.
