### ISSUE TITLE
Allow ApplicationNavigation items to open in new tabs/windows

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-application#40]
# Feature Request

## Description
The navigation items in ApplicationNavigation are not links like normal navigation items. As a result, when you try to right-click or Ctrl/Cmd+click them to open in a new tab/window. The navigation items should be links so that they can perform like a normal link that users expect.

## Additional Context / Screenshots
My team can help assist with this contribution if you all agree with it.

**Comment by ryanthemanuel** [comment]
Had a conversation about this in person on 5/14 and decided that we were not going to be doing this at this time due to concerns about how it fits into the overall vision of app navigation.  Closing this.
