### ISSUE TITLE
Expose ApplicationBase props to allow customization of default ApplicationLoadingOverlayProvider/ApplicationErrorBoundary implementations

### ISSUE THREAD

**Issue by tbiethman** [cerner/terra-application#44]
# Feature Request

## Description

ApplicationBase is mostly UI-agnostic, beyond the default inclusion of ApplicationLoadingOverlayProvider and ApplicationErrorBoundary in the component stack. While we definitely want to ensure a boundary is in place, and that the loading overlay APIs are available, providing these APIs without a chance to override their associated UI limits where ApplicationBase can be used. 

I propose we add `renderLoadingOverlayProvider`/`renderErrorBoundary` props to ApplicationBase that allows consumers to swap out the default implementations. Default prop values could be added with the current implementation to minimally impact existing consumers.

**Comment by ryanthemanuel** [comment]
Our use case for this is no longer needed.  Closing this for now.
