### ISSUE TITLE
Investigate our options for focus with terra-application-error-boundary

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-application#56]
# Feature Request

Currently, it is indeterminate what happens to the active element when the error boundary shows (in chrome and firefox it goes to body, in ie it clears it).  We should figure out if there's something we can do better here.

**Comment by dkasper-was-taken** [comment]
Initial behavior spike:

**VoiceOver:**
Safari:
**No announcement** of error display.
Sequential navigation resumes **before** the error message, allowing it be be read.

Chrome:
**No announcement** of error display.
Sequential navigation resumes **after** the error message, stating it is the end of main container.

**Jaws:**
IE10:
**No announcement** of error display.
Sequential navigation resumes **after** the error message, stating it is the end of main container.

Chrome:
**No announcement** of error display.
Sequential navigation resumes **after** the error message, stating it is the end of main container.

**Comment by tbiethman** [comment]
We met with @scottwilmarth yesterday to discuss what should be done here. Takeaways are:

* The error boundary content needs to be read, one way or another.
* Focus should be moved to either the root of the app (for page-level error boundaries) or to the root of the modal (for modal-presented error boundaries).
  * If this isn't feasible, we could investigate focusing the error boundary container itself.

**Comment by lokesh-0813** [comment]
@tbiethman Will there be a situation where consumer might have a scenario with more than one error boundary ?

Something like, 

```
<ErrorBoundary>
  <MyComponent1 />
<ErrorBoundary/>
<ErrorBoundary>
  <MyComponent2 />
<ErrorBoundary/>
```

**Comment by tbiethman** [comment]
There will be more than one error boundary present, but I wouldn't expect more than one ApplicationErrorBoundary active at any given time. There definitely could be multiple error boundaries active at some point in the future (like in multiple cells in a grid-like dashboard or something), but I wouldn't expect those to be using the ApplicationErrorBoundary. I think the results of this spike will indicate that we need to create more tailored error boundary components for specific use cases.
