### ISSUE TITLE
Font-family is overridden by other frameworks

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-application#6]
If I include bootstrap or foundation, the font-family provided by terra-application is overridden. I would like terra-application to have higher specificity for font-family.

**Comment by bjankord** [comment]
Looking at [what Bootstrap is doing](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L57-L80) and [what Foundation is doing](https://github.com/zurb/foundation-sites/blob/master/scss/_global.scss#L124-L150) with these types of styles, I'm thinking we should move `background-color, color, font-family, and font-size` styles in `.terra-Application` to `.terra-Application > body`. We'll want to keep `font-size` set in `.terra-Application` so rem units work as expected but also define it in body to override how its set in other frameworks.
