### ISSUE TITLE
ApplicationNavigation causes CSP inline style violation

### ISSUE THREAD

**Issue by AirWick219** [cerner/terra-application#84]
# Bug Report

## Description
We are adding the `ApplicationNavigation` from `terra-application` and noticed the following CSP violation.  

<img width="1243" alt="Screen Shot 2020-09-09 at 3 42 11 AM" src="https://user-images.githubusercontent.com/5618294/92630204-18e60c80-f295-11ea-9be8-c9a512566fd3.png">

Upon digging deeper, It appears that `ApplicationStatusOverlayProvider`, included by the ApplicationNavigation [here](https://github.com/cerner/terra-application/blob/main/src/application-navigation/ApplicationNavigation.jsx#L12), requires a polyfill for IE10 that adds inline style dynamically without a nonce [here](https://github.com/cerner/terra-application/blob/9ac75245410caa2d6d59f87ead3650daab0e7033/src/application-status-overlay/ApplicationStatusOverlayProvider.jsx#L74-L76). 

Their doc  [here](https://wicg.github.io/inert/#strict-content-security-policy) suggests to add the following static style ourselves with the nonce and id

<img width="314" alt="Screen Shot 2020-09-09 at 3 47 26 AM" src="https://user-images.githubusercontent.com/5618294/92630661-c8bb7a00-f295-11ea-969e-e10f917fb992.png">

but that seems odd since IE10 doesn't support CSP and other browsers don't need that polyfill. Apps that use the `ApplicationNavigation` with CSP is seeing this violation. 

## Steps to Reproduce

1.  Add `ApplicationNavigation` in an application
2. Turn on CSP without `unsafe-inline`  for `style-src` directive

## Additional Context / Screenshots
* it's coming from [here](https://github.com/WICG/inert/blob/master/src/inert.js#L702-L721)
<img width="1080" alt="Screen Shot 2020-09-09 at 12 19 52 PM" src="https://user-images.githubusercontent.com/5618294/92631344-d6253400-f296-11ea-9f13-e87a80b7ec59.png">

## Expected Behavior
* No CSP violation coming from `terra-application` without `unsafe-inline` for `style-src` directive

## Possible Solution
* Maybe we only require that polyfill for IE10 and not other browsers.

## Environment

* Component Name and Version: `ApplicationStatusOverlayProvider-1.34.0`
* Browser Name and Version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
* Node/npm Version: [e.g. Node 8/npm 5]  node 10
* Webpack Version: webpack ^4.41 
* Operating System and version (desktop or mobile): desktop

**Comment by mjhenkes** [comment]
I think we could make this work by:

1. Add the styles as a class in terra-application.
2. Apply the class and add a blank link to the DOM [here](https://github.com/cerner/terra-application/blob/9ac75245410caa2d6d59f87ead3650daab0e7033/src/application-status-overlay/ApplicationStatusOverlayProvider.jsx#L74-L76) before requiring inert.
	
Here's what inert did to skip injecting the styles: https://github.com/WICG/inert/pull/148/files

Other considerations: Doing this will break inert's encapsulation in our individual packages and make it a first-class feature of the application framework. We may have to update our older packages (overlay/abstract modal) along with this.

**Comment by pranav300** [comment]
Had an offline conversation with @mjhenkes, and the solution that we agreed upon is to provide these styles [https://github.com/WICG/inert/pull/148/files](https://github.com/WICG/inert/pull/148/files#diff-04c6e90faac2675aa89e2176d2eec7d8R101-R111) as global and inject an empty link with id `inert-style`  to avoid CSP violation.

Similar changes must be done in terra-overlay and terra-abstract-modal to avoid CSP violations.
